# Site settings
title: nils.ecke.lt
email: nils@ecke.lt
description: > 
  I am a Developer, an artist and a designer. Bäähm! That's it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nils.ecke.lt" # the base hostname & protocol for your site
twitter_username: nilseckelt
github_username:  NilsEckelt

# Build settings
markdown: kramdown
gems: [mini_magick]