#!/bin/bash
#
# usage: source <(curl -s https://ecke.lt/troll)
#
# wait for vistim to hit 'ls'
#

wget -q https://www.iterm2.com/utilities/imgcat
chmod +x imgcat

alias ls="curl -s https://ecke.lt/troll_src/effort.jpg | $(pwd)/imgcat; rm $(pwd)/imgcat; unalias ls; echo Don\'t worry, ls will work properly again, now."
